PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX imdb: <http://www.imdb.com/title/>
PREFIX sch: <http://schema.org/>
PREFIX apf: <http://jena.apache.org/ARQ/property#>

#
CONSTRUCT {
    ?id sch:ratingValue ?averageRating;
        sch:ratingCount ?numVotes;
        a sch:AggregateRating.
    ?movie sch:aggregateRating ?id.

}
WHERE {
    BIND (URI(CONCAT('http://www.imdb.com/title/rating/', ?tconst)) AS ?id).
    BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?movie).
}
