PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX imdb: <http://www.imdb.com/title/>
PREFIX sch: <http://schema.org/>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX swnw: <http://swnw.eu/>
#Movie type, title, pubication date
CONSTRUCT {
    ?id a sch:Movie;
        sch:name ?originalTitle;
        sch:datePublished ?dateStartYear;
        swnw:type ?titleType.
}
WHERE {
    BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?id).
    BIND (STRDT(STR(?startYear), sch:Date) AS ?datStartYear).
}

#split genres
CONSTRUCT {
    ?id sch:genre ?genre.
}
WHERE {
    BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?id).
    OPTIONAL { ?genre apf:strSplit (?genres ","). FILTER (?genres != '\\N')}
}

#duration if exists
CONSTRUCT {
    ?id sch:duration ?duration.
}
WHERE {
    BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?id).
    BIND (STRDT(CONCAT("PT", CONCAT(?runtimeMinutes, "M")), sch:Duration) AS ?duration).
    FILTER (?runtimeMinutes!="\\N").
}
