PREFIX sch: <http://schema.org/>
PREFIX swnw: <http://swnw.eu/>

SELECT ?director (COUNT(?id) AS ?nbFilms)
WHERE {
	?id sch:director ?director.
  	?id swnw:type "movie"
}
GROUP BY ?director
ORDER BY DESC( ?nbFilms)
LIMIT 5
