PREFIX sch: <http://schema.org/>
PREFIX swnw: <http://swnw.eu/>

SELECT (COUNT( DISTINCT ?name ) AS ?nbFilms)
WHERE {
	?id sch:countryOfOrigin ?country;
		sch:name ?name;
		swnw:type ?type.
	FILTER (?country = "ES").
	FILTER (?type = "short").
}
